-- VHDL module instantiation generated by SCUBA Diamond (64-bit) 3.11.3.469
-- Module  Version: 7.5
-- Thu Jun 09 19:08:05 2022

-- parameterized module component declaration
component byte_cache_32
    port (Clock: in  std_logic; ClockEn: in  std_logic; 
        Reset: in  std_logic; ByteEn: in  std_logic_vector(3 downto 0); 
        WE: in  std_logic; Address: in  std_logic_vector(11 downto 0); 
        Data: in  std_logic_vector(31 downto 0); 
        Q: out  std_logic_vector(31 downto 0));
end component;

-- parameterized module component instance
__ : byte_cache_32
    port map (Clock=>__, ClockEn=>__, Reset=>__, ByteEn(3 downto 0)=>__, 
        WE=>__, Address(11 downto 0)=>__, Data(31 downto 0)=>__, Q(31 downto 0)=>__);
