-- VHDL module instantiation generated by SCUBA Diamond (64-bit) 3.10.3.144
-- Module  Version: 7.5
-- Sat Nov 16 18:21:30 2019

-- parameterized module component declaration
component internal_datamem_32
    port (Clock: in  std_logic; ClockEn: in  std_logic; 
        Reset: in  std_logic; WE: in  std_logic; 
        Address: in  std_logic_vector(11 downto 0); 
        Data: in  std_logic_vector(31 downto 0); 
        Q: out  std_logic_vector(31 downto 0));
end component;

-- parameterized module component instance
__ : internal_datamem_32
    port map (Clock=>__, ClockEn=>__, Reset=>__, WE=>__, Address(11 downto 0)=>__, 
        Data(31 downto 0)=>__, Q(31 downto 0)=>__);
