-- VHDL module instantiation generated by SCUBA Diamond (64-bit) 3.10.3.144
-- Module  Version: 7.5
-- Wed Apr 22 18:22:23 2020

-- parameterized module component declaration
component internal_datamem_18
    port (DataInA: in  std_logic_vector(17 downto 0); 
        DataInB: in  std_logic_vector(17 downto 0); 
        AddressA: in  std_logic_vector(12 downto 0); 
        AddressB: in  std_logic_vector(12 downto 0); 
        ClockA: in  std_logic; ClockB: in  std_logic; 
        ClockEnA: in  std_logic; ClockEnB: in  std_logic; 
        WrA: in  std_logic; WrB: in  std_logic; ResetA: in  std_logic; 
        ResetB: in  std_logic; QA: out  std_logic_vector(17 downto 0); 
        QB: out  std_logic_vector(17 downto 0));
end component;

-- parameterized module component instance
__ : internal_datamem_18
    port map (DataInA(17 downto 0)=>__, DataInB(17 downto 0)=>__, 
        AddressA(12 downto 0)=>__, AddressB(12 downto 0)=>__, ClockA=>__, 
        ClockB=>__, ClockEnA=>__, ClockEnB=>__, WrA=>__, WrB=>__, ResetA=>__, 
        ResetB=>__, QA(17 downto 0)=>__, QB(17 downto 0)=>__);
