-- VHDL module instantiation generated by SCUBA Diamond (64-bit) 3.11.3.469
-- Module  Version: 7.5
-- Sun Jul 10 18:44:55 2022

-- parameterized module component declaration
component byte_cache_16
    port (DataInA: in  std_logic_vector(15 downto 0); 
        DataInB: in  std_logic_vector(15 downto 0); 
        ByteEnA: in  std_logic_vector(1 downto 0); 
        ByteEnB: in  std_logic_vector(1 downto 0); 
        AddressA: in  std_logic_vector(12 downto 0); 
        AddressB: in  std_logic_vector(12 downto 0); 
        ClockA: in  std_logic; ClockB: in  std_logic; 
        ClockEnA: in  std_logic; ClockEnB: in  std_logic; 
        WrA: in  std_logic; WrB: in  std_logic; ResetA: in  std_logic; 
        ResetB: in  std_logic; QA: out  std_logic_vector(15 downto 0); 
        QB: out  std_logic_vector(15 downto 0));
end component;

-- parameterized module component instance
__ : byte_cache_16
    port map (DataInA(15 downto 0)=>__, DataInB(15 downto 0)=>__, 
        ByteEnA(1 downto 0)=>__, ByteEnB(1 downto 0)=>__, AddressA(12 downto 0)=>__, 
        AddressB(12 downto 0)=>__, ClockA=>__, ClockB=>__, ClockEnA=>__, 
        ClockEnB=>__, WrA=>__, WrB=>__, ResetA=>__, ResetB=>__, QA(15 downto 0)=>__, 
        QB(15 downto 0)=>__);
