-- VHDL module instantiation generated by SCUBA Diamond (64-bit) 3.10.1.112
-- Module  Version: 7.5
-- Wed Jan 23 19:26:45 2019

-- parameterized module component declaration
component internal_Datamem_27
    port (DataInA: in  std_logic_vector(26 downto 0); 
        DataInB: in  std_logic_vector(26 downto 0); 
        AddressA: in  std_logic_vector(11 downto 0); 
        AddressB: in  std_logic_vector(11 downto 0); 
        ClockA: in  std_logic; ClockB: in  std_logic; 
        ClockEnA: in  std_logic; ClockEnB: in  std_logic; 
        WrA: in  std_logic; WrB: in  std_logic; ResetA: in  std_logic; 
        ResetB: in  std_logic; QA: out  std_logic_vector(26 downto 0); 
        QB: out  std_logic_vector(26 downto 0));
end component;

-- parameterized module component instance
__ : internal_Datamem_27
    port map (DataInA(26 downto 0)=>__, DataInB(26 downto 0)=>__, 
        AddressA(11 downto 0)=>__, AddressB(11 downto 0)=>__, ClockA=>__, 
        ClockB=>__, ClockEnA=>__, ClockEnB=>__, WrA=>__, WrB=>__, ResetA=>__, 
        ResetB=>__, QA(26 downto 0)=>__, QB(26 downto 0)=>__);
